# Generated by Django 3.1 on 2021-04-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('america_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
    ]
